import * as XLSX from "xlsx";
import { ProcessedContent } from "../processors";

function autoColumnWidths(ws: XLSX.WorkSheet): XLSX.ColInfo[] {
  const range = XLSX.utils.decode_range(ws["!ref"] || "A1");
  const widths: XLSX.ColInfo[] = [];

  for (let C = range.s.c; C <= range.e.c; C++) {
    let max = 8;
    for (let R = range.s.r; R <= range.e.r; R++) {
      const cell = ws[XLSX.utils.encode_cell({ r: R, c: C })];
      if (cell && cell.v != null) {
        const len = String(cell.v).length;
        if (len > max) max = len;
      }
    }
    widths.push({ wch: Math.min(max + 2, 50) });
  }
  return widths;
}

function applyHeaderStyle(ws: XLSX.WorkSheet) {
  const range = XLSX.utils.decode_range(ws["!ref"] || "A1");
  for (let C = range.s.c; C <= range.e.c; C++) {
    const cell = ws[XLSX.utils.encode_cell({ r: 0, c: C })];
    if (cell) {
      cell.s = {
        font: { bold: true, color: { rgb: "0A1628" } },
        fill: { fgColor: { rgb: "E8F4FD" }, patternType: "solid" },
        alignment: { horizontal: "center", vertical: "center", wrapText: true },
        border: {
          bottom: { style: "medium", color: { rgb: "00D4FF" } },
          top: { style: "thin", color: { rgb: "CCCCCC" } },
          left: { style: "thin", color: { rgb: "CCCCCC" } },
          right: { style: "thin", color: { rgb: "CCCCCC" } },
        },
      };
    }
  }
  // Zebra striping on data rows
  for (let R = 1; R <= range.e.r; R++) {
    for (let C = range.s.c; C <= range.e.c; C++) {
      const cell = ws[XLSX.utils.encode_cell({ r: R, c: C })];
      if (cell) {
        cell.s = {
          fill: R % 2 === 0 ? { fgColor: { rgb: "F7FAFC" }, patternType: "solid" } : undefined,
          border: {
            bottom: { style: "thin", color: { rgb: "EEEEEE" } },
            left: { style: "thin", color: { rgb: "EEEEEE" } },
            right: { style: "thin", color: { rgb: "EEEEEE" } },
          },
          alignment: { vertical: "top", wrapText: false },
        };
      }
    }
  }
}

function detectAndSetTypes(ws: XLSX.WorkSheet) {
  const range = XLSX.utils.decode_range(ws["!ref"] || "A1");
  for (let R = range.s.r + 1; R <= range.e.r; R++) {
    for (let C = range.s.c; C <= range.e.c; C++) {
      const cell = ws[XLSX.utils.encode_cell({ r: R, c: C })];
      if (cell && cell.t === "s") {
        const v = cell.v as string;
        const num = parseFloat(v);
        if (!isNaN(num) && v.trim() !== "") {
          cell.t = "n";
          cell.v = num;
          if (v.includes(".")) cell.z = "#,##0.00";
        }
      }
    }
  }
}

export async function generateXlsx(content: ProcessedContent, originalName: string): Promise<Buffer> {
  const wb = XLSX.utils.book_new();

  if (content.tables && content.tables.length > 0) {
    content.tables.forEach((tableData, index) => {
      if (!Array.isArray(tableData) || tableData.length === 0) return;
      const ws = XLSX.utils.aoa_to_sheet(tableData as unknown[][]);
      detectAndSetTypes(ws);
      ws["!cols"] = Object.values(autoColumnWidths(ws));
      ws["!rows"] = [{ hpt: 22 }]; // taller header row
      applyHeaderStyle(ws);
      const sheetName = `Sheet${index + 1}`.substring(0, 31);
      XLSX.utils.book_append_sheet(wb, ws, sheetName);
    });
  } else {
    // Parse CSV-like text into structured data
    const lines = content.text.split("\n").filter((l) => l.trim());
    const rows: string[][] = lines.map((line) => {
      if (line.includes("\t")) return line.split("\t");
      if (line.includes("|")) return line.split("|").map((c) => c.trim()).filter(Boolean);
      if (line.includes(",")) return line.split(",").map((c) => c.trim());
      return [line];
    });

    const ws = XLSX.utils.aoa_to_sheet([
      [`Recovered: ${originalName.replace(/\.[^.]+$/, "")}`],
      [`Generated by Nexus Revive on ${new Date().toLocaleDateString()}`],
      [],
      ...rows,
    ]);
    detectAndSetTypes(ws);
    ws["!cols"] = Object.values(autoColumnWidths(ws));
    ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 4 } }];
    applyHeaderStyle(ws);
    XLSX.utils.book_append_sheet(wb, ws, "Recovered Data");
  }

  // Add metadata sheet with branding
  const meta = XLSX.utils.aoa_to_sheet([
    ["Property", "Value"],
    ["Original File", originalName],
    ["Recovered By", "Nexus Revive"],
    ["Date", new Date().toISOString()],
    ["Word Count", content.wordCount ?? "N/A"],
    ["Encoding", content.encoding ?? "UTF-8"],
    [],
    ["nexusrevive.com", "Resurrect Any File. From Any Era."],
  ]);
  meta["!cols"] = [{ wch: 20 }, { wch: 40 }];
  applyHeaderStyle(meta);
  XLSX.utils.book_append_sheet(wb, meta, "Metadata");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx", bookSST: false }) as Buffer;
  if (!buffer || buffer.length === 0) throw new Error("Failed to generate XLSX");
  return buffer;
}
